import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
	AiFillTwitterCircle,
	AiFillYoutube,
	AiFillFacebook,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { use, useState } from "react";

export default function Home() {
	const [darkMode, setDarkMode] = useState(false);
	return (
		<div className={darkMode ? "dark" : ""}>
			<Head>
				<title>Loc Son Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="bg-[#f8f9fa] px-10 md:px-20 lg:px-40 dark:bg-[#17223b] dark:text-[#FFF7D6]">
				<section className="min-h-screen">
					<nav className="py-10 mb-12 flex justify-between ">
						<h1 className=" text-xl font-burtons">developed</h1>
						<ul className="flex items-center">
							<li>
								<BsFillMoonStarsFill
									onClick={() => setDarkMode(!darkMode)}
									className="cursor-pointer text-2xl"
								/>
							</li>
							<li>
								<a
									href="#"
									className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
								>
									Resume
								</a>
							</li>
						</ul>
					</nav>
					<div className="text-center p-10">
						<h2 className="text-5xl py2 text-teal-600 font-medium md:text-6xl dark:text-[#00C6BF]">
							Loc Son
						</h2>
						<h3 className="text-2xl py-2 md:text-3xl">
							Developer and designer.
						</h3>
						<p className="font-medium py-5 leading-8 text-[#212529] md:text-xl max-w-xl mx-auto dark:text-[#FFF7D6]">
							Freelancer providing services for programming and design content
							needs. Join me down below and let's get cracking
						</p>
					</div>
					<div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
						<AiFillTwitterCircle className="dark:text-[#FFF7D6]" />
						<AiFillFacebook className="dark:text-[#FFF7D6]" />
						<AiFillYoutube className="dark:text-[#FFF7D6]" />
					</div>
					<div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
						<Image src={deved} alt="deved" layout="fill" objectFit="cover" />
					</div>
				</section>

				<section>
					<div>
						<h3 className="text-3xl py-1">Services I offer</h3>
						<p className="text-base py-2 leading-8 text-gray-80 dark:text-[#f2e9e4]">
							Since the beginning of my journey as a freelancer designer and
							developer, I've done remote work for
							<span className="text-teal-500 dark:text-[#00C6BF]">
								{" "}
								agencies{" "}
							</span>{" "}
							consulted for{" "}
							<span className="text-teal-500 dark:text-[#00C6BF]">
								startups
							</span>{" "}
							and collaborated with talented people to create digital products
							for both business and consumer use.
						</p>
						<p className="text-base py-2 leading-8 text-gray-80 dark:text-[#f2e9e4]">
							I offer from a wide range of services, include brand design,
							programming and teaching
						</p>
					</div>
					<div className="lg:flex gap-10">
						<div className="flex flex-col items-center shadow-lg p-10 rounded-xl my-10 dark:bg-[#E3F4F3] dark:text-[#17223B]">
							<Image src={design} width={100} height={100} alt="Design" />
							<h3 className="text-lg font-medium pt-8 pb-2">
								Beautiful Designs
							</h3>
							<p className="py-2">
								Create elegant designs suited for your needs following core
								design theory
							</p>
							<h4 className="py-4 text-teal-600">Design tools I use</h4>
							<p className="text-gray-800 py-1">Photoshop</p>
							<p className="text-gray-800 py-1">Illustrator</p>
							<p className="text-gray-800 py-1">Figma</p>
						</div>
						<div className="flex flex-col items-center shadow-lg p-10 rounded-xl my-10 dark:bg-[#E3F4F3] dark:text-[#17223B]">
							<Image src={code} width={100} height={100} alt="Design" />
							<h3 className="text-lg font-medium pt-8 pb-2">
								Beautiful Designs
							</h3>
							<p className="py-2">
								Create elegant designs suited for your needs following core
								design theory
							</p>
							<h4 className="py-4 text-teal-600">Design tools I use</h4>
							<p className="text-gray-800 py-1">Photoshop</p>
							<p className="text-gray-800 py-1">Illustrator</p>
							<p className="text-gray-800 py-1">Figma</p>
						</div>
						<div className="flex flex-col items-center shadow-lg p-10 rounded-xl my-10 dark:bg-[#E3F4F3] dark:text-[#17223B]">
							<Image src={consulting} width={100} height={100} alt="Design" />
							<h3 className="text-lg font-medium pt-8 pb-2">
								Beautiful Designs
							</h3>
							<p className="py-2">
								Create elegant designs suited for your needs following core
								design theory
							</p>
							<h4 className="py-4 text-teal-600">Design tools I use</h4>
							<p className="text-gray-800 py-1">Photoshop</p>
							<p className="text-gray-800 py-1">Illustrator</p>
							<p className="text-gray-800 py-1">Figma</p>
						</div>
					</div>
				</section>

				<section>
					<div>
						<h3 className="text-3xl py-1">Portfolio</h3>
						<p className="text-base py-2 leading-8 text-gray-80 dark:text-[#f2e9e4]">
							Since the beginning of my journey as a freelancer designer and
							developer, I've done remote work for
							<span className="text-teal-500 dark:text-[#00C6BF]">
								{" "}
								agencies{" "}
							</span>{" "}
							consulted for{" "}
							<span className="text-teal-500 dark:text-[#00C6BF]">
								startups
							</span>{" "}
							and collaborated with talented people to create digital products
							for both business and consumer use.
						</p>
						<p className="text-base py-2 leading-8 text-gray-80 dark:text-[#f2e9e4]">
							I offer from a wide range of services, include brand design,
							programming and teaching
						</p>
					</div>
					<div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
						<div className="basis-1/3 flex-1">
							<Image
								src={web1}
								className="rounded-lg object-cover"
								width={"100%"}
								height={"100%"}
								layout="responsive"
								alt="web1"
							/>
						</div>
						<div className="basis-1/3 flex-1">
							<Image
								src={web2}
								className="rounded-lg object-cover"
								width={"100%"}
								height={"100%"}
								layout="responsive"
								alt="web2"
							/>
						</div>
						<div className="basis-1/3 flex-1">
							<Image
								src={web3}
								className="rounded-lg object-cover"
								width={"100%"}
								height={"100%"}
								layout="responsive"
								alt="web3"
							/>
						</div>
						<div className="basis-1/3 flex-1">
							<Image
								src={web4}
								className="rounded-lg object-cover"
								width={"100%"}
								height={"100%"}
								layout="responsive"
								alt="web4"
							/>
						</div>
						<div className="basis-1/3 flex-1">
							<Image
								src={web5}
								className="rounded-lg object-cover"
								width={"100%"}
								height={"100%"}
								layout="responsive"
								alt="web5"
							/>
						</div>
						<div className="basis-1/3 flex-1">
							<Image
								src={web6}
								className="rounded-lg object-cover"
								width={"100%"}
								height={"100%"}
								layout="responsive"
								alt="web6"
							/>
						</div>
					</div>
				</section>
			</main>
		</div>
	);
}
